from __future__ import annotations

from src.core.localization.localization_table import LocalizationTable


def BuildEnglishTable() -> LocalizationTable:
    return LocalizationTable(
        "en",
        {
            # Main window
            "main.title": "Stream Controller",
            "main.header.title": "Stream Controller",
            "main.button.exit": "Exit",
            "main.tab.dashboard": "Dashboard",
            "main.tab.twitch": "Twitch",
            "main.tab.windows": "Windows",
            "main.tab.balances": "Balances",
            "main.dashboard.showOverlay": "Show Overlay (Sample)",
            "main.dashboard.twitchStatus.unknown": "Twitch: unknown",
            "main.dashboard.connect": "Connect",
            "main.dashboard.disconnect": "Disconnect",
            "main.dashboard.settings": "Settings",
            "main.twitch.title": "Twitch Connection",
            "main.twitch.help": "Configure token/nick/channel in Settings. Connection runs in background thread; UI stays responsive.",
            "main.twitch.statusLabel": "Status:",
            "main.twitch.openChat": "Open Chat Log",
            "main.windows.chat": "Chat",
            "main.windows.events": "Events",
            "main.windows.settings": "Settings",
            "main.status.connectRequested": "Connect requested",
            "main.status.disconnectRequested": "Disconnect requested",
            "main.twitch.prefix": "Twitch: {summary}",
            "main.twitch.configured": "Configured for {channel}",
            "main.twitch.missingConfig": "Twitch not configured",
            "main.dialog.twitch.title": "Twitch",

            # Balances tab
            "balances.title": "User balances",
            "balances.button.refresh": "Refresh",
            "balances.column.user": "User",
            "balances.column.balance": "Balance",
            "balances.empty": "No balances recorded yet",

            # Earnings tab
            "earnings.title": "Silver earnings",
            "earnings.button.refresh": "Refresh",
            "earnings.button.apply": "Apply",
            "earnings.label.chat": "Silver per chat message",
            "earnings.label.vote": "Silver per poll vote",
            "earnings.label.cooldown": "Chat reward cooldown (seconds)",
            "earnings.help": "Updates apply immediately and only affect new earnings. Balances are not modified retroactively.",
            "earnings.status.saved": "Saved",
            "earnings.status.error": "Check values",
            "earnings.error.title": "Invalid values",
            "earnings.error.invalid": "Please enter numeric values.",
            "earnings.error.negative": "Values must be zero or higher.",

            # Settings window
            "settings.title": "Settings",
            "settings.tab.twitch": "Twitch",
            "settings.tab.overlay": "Overlay",
            "settings.tab.rimworld": "RimWorld",
            "settings.tab.earnings": "Earnings",
            "settings.twitch.channel": "Channel",
            "settings.twitch.botUsername": "Bot username",
            "settings.twitch.oauthToken": "OAuth token",
            "settings.twitch.showToken": "Show token",
            "settings.overlay.borderless": "Borderless overlay",
            "settings.overlay.chroma": "Enable chroma key overlay",
            "settings.overlay.chromaCount": "Last voters to show (0-3)",
            "settings.overlay.uiLanguage": "UI language",
            "settings.rimworld.host": "RimWorld REST host",
            "settings.rimworld.port": "RimWorld REST port",
            "settings.button.cancel": "Cancel",
            "settings.button.save": "Save",

            # Chat window
            "chat.title": "Chat Log",
            "chat.header.title": "Recent messages",
            "chat.button.close": "Close",
            "chat.tab.messages": "Messages",
            "chat.tab.status": "Status",
            "chat.status.waiting": "Waiting for connection",

            # Events window
            "events.title": "Events",
            "events.button.reload": "Reload",
            "events.button.openFile": "Open File",
            "events.button.close": "Close",
            "events.tab.catalog": "Catalog",
            "events.tab.random": "Random",
            "events.tab.editor": "Editor",
            "events.status.loaded": "Loaded {normalCount} normal + {randomCount} random",
            "events.status.reloadFailed": "Reload failed: {error}",
            "events.status.noVisibleEvents": "No visible events to test",
            "events.status.noEventSelected": "No event selected",
            "events.status.opened": "Opened: {name}",
            "events.status.openFailed": "Open failed: {error}",
            "events.details.noEventsLoaded": "No events loaded",
            "events.details.noEventSelected": "No event selected",

            # Events catalog tab
            "events.catalog.search": "Search",
            "events.catalog.kind.normal": "Normal",
            "events.catalog.kind.random": "Random",
            "events.catalog.column.type": "Type",
            "events.catalog.column.label": "Label",
            "events.catalog.column.id": "Id",
            "events.catalog.column.cost": "Cost",
            "events.catalog.column.prob": "Prob",
            "events.catalog.details.title": "Definition",
            "events.catalog.button.copyId": "Copy Id",
            "events.catalog.button.copyJson": "Copy JSON",
            "events.catalog.button.testAll.ready": "Test All (x5)",
            "events.catalog.button.testAll.armed": "Test All ({count}/5)",
            "events.catalog.details.noMatching": "No matching events",

            # Events random tab
            "events.random.endpoint.label": "RimWorld endpoint:",
            "events.random.endpoint.help": "(configure in Settings)",
            "events.random.header.tags": "Tags",
            "events.random.header.enabled": "Enabled events",
            "events.random.tags.search": "Search",
            "events.random.tags.all": "All",
            "events.random.tags.none": "None",
            "events.random.tags.noMatch": "No tags match",
            "events.random.enabled.search": "Search",
            "events.random.enabled.toggleHint": "Double-click or Space to toggle",
            "events.random.controls.duration": "Duration (sec)",
            "events.random.controls.start": "Start",
            "events.random.controls.stop": "Stop",
            "events.random.status.votingStarted": "Voting started",
            "events.random.status.stopped": "Stopped",
            "events.random.status.noEnabled": "No enabled events (check tags)",
            "events.random.status.newRound": "New round started",
            "events.random.status.noWinner": "No winner (no votes)",
            "events.random.status.executed": "Executed: {display} ({summary})",
            "events.random.status.executionFailed": "Execution failed: {error}",

            # Events editor tab
            "events.editor.templates": "Templates",
            "events.editor.search": "Search",
            "events.editor.button.copyJson": "Copy JSON",
            "events.editor.button.execute": "Execute",
            "events.editor.button.refreshLists": "Refresh Lists",
            "events.editor.details.title": "Details",
            "events.editor.badge.templateId": "Id: {templateId}",
            "events.editor.badge.modified": "Modified",
            "events.editor.preview.title": "Generated JSON",
            "events.editor.parameters.endpoint": "Endpoint: {endpoint}",
            "events.editor.status.refreshedLookups": "Refreshed lookups",
            "events.editor.status.templateBuildFailed": "Template build failed: {error}",
            "events.editor.preview.noTemplateSelected": "No template selected",
            "events.editor.status.copiedJson": "Copied JSON",
            "events.editor.status.invalidEventJson": "Invalid event JSON: {error}",
            "events.editor.status.executed": "Executed: {label} ({summary})",
            "events.editor.status.executeFailed": "Execute failed: {error}",
            # Protection status
            "protection.label.unknown": "Protection: ?",
            "protection.label.off": "Protection: OFF",
            "protection.label.external": "Protection: EXTERNAL ({seconds}s)",
            "protection.label.allBad": "Protection: ALL BAD ({seconds}s)",
            "protection.label.error": "Protection: {message}",
            "protection.error.unavailable": "unavailable",
            # Event tester
            "eventTest.running": "Testing {count} events… writing {fileName}",
            "eventTest.progress": "[{index}/{count}] {label} ({seconds:.1f}s)",
            "eventTest.complete": "Test run complete: {path}",
            "eventTest.failed": "Test run failed: {error}",

            # Overlay
            "overlay.title": "Stream Votes Overlay",
            "overlay.button.close": "Close",
            "overlay.poll.title": "Stream Poll",
            "overlay.poll.totalVotes": "Total votes: {count}",
            "overlay.poll.waitingVotes": "Waiting for votes",
            "overlay.poll.noOptions": "No options",
            "overlay.poll.recentVotersPrefix": "Recent",
        },
    )
