from __future__ import annotations

from src.core.localization.localization_table import LocalizationTable


def BuildRussianTable() -> LocalizationTable:
    return LocalizationTable(
        "ru",
        {
            # Main window
            "main.title": "Пульт стрима",
            "main.header.title": "Пульт стрима",
            "main.button.exit": "Выход",
            "main.tab.dashboard": "Панель",
            "main.tab.twitch": "Twitch",
            "main.tab.windows": "Окна",
            "main.tab.balances": "Баланс",
            "main.dashboard.showOverlay": "Показать оверлей (пример)",
            "main.dashboard.twitchStatus.unknown": "Twitch: неизвестно",
            "main.dashboard.connect": "Подключить",
            "main.dashboard.disconnect": "Отключить",
            "main.dashboard.settings": "Настройки",
            "main.twitch.title": "Подключение к Twitch",
            "main.twitch.help": "Настройте token/nick/channel в Настройках. Подключение выполняется в фоновом потоке; интерфейс остаётся отзывчивым.",
            "main.twitch.statusLabel": "Статус:",
            "main.twitch.openChat": "Открыть чат",
            "main.windows.chat": "Чат",
            "main.windows.events": "События",
            "main.windows.settings": "Настройки",
            "main.status.connectRequested": "Запрошено подключение",
            "main.status.disconnectRequested": "Запрошено отключение",
            "main.twitch.prefix": "Twitch: {summary}",
            "main.twitch.configured": "Настроено для {channel}",
            "main.twitch.missingConfig": "Twitch не настроен",
            "main.dialog.twitch.title": "Twitch",

            # Balances tab
            "balances.title": "Баланс пользователей",
            "balances.button.refresh": "Обновить",
            "balances.column.user": "Пользователь",
            "balances.column.balance": "Баланс",
            "balances.empty": "Балансов пока нет",

            # Settings window
            "settings.title": "Настройки",
            "settings.tab.twitch": "Twitch",
            "settings.tab.overlay": "Оверлей",
            "settings.tab.rimworld": "RimWorld",
            "settings.twitch.channel": "Канал",
            "settings.twitch.botUsername": "Имя бота",
            "settings.twitch.oauthToken": "OAuth токен",
            "settings.twitch.showToken": "Показать токен",
            "settings.overlay.borderless": "Оверлей без рамки",
            "settings.overlay.chroma": "Включить хромакей",
            "settings.overlay.chromaCount": "Сколько последних голосовавших показывать (0-3)",
            "settings.overlay.uiLanguage": "Язык интерфейса",
            "settings.rimworld.host": "RimWorld REST хост",
            "settings.rimworld.port": "RimWorld REST порт",
            "settings.button.cancel": "Отмена",
            "settings.button.save": "Сохранить",

            # Chat window
            "chat.title": "Журнал чата",
            "chat.header.title": "Последние сообщения",
            "chat.button.close": "Закрыть",
            "chat.tab.messages": "Сообщения",
            "chat.tab.status": "Статус",
            "chat.status.waiting": "Ожидание подключения",

            # Events window (already present keys)
            "events.title": "События",
            "events.button.reload": "Обновить",
            "events.button.openFile": "Открыть файл",
            "events.button.close": "Закрыть",
            "events.tab.catalog": "Каталог",
            "events.tab.random": "Случайные",
            "events.tab.editor": "Редактор",
            "events.status.loaded": "Загружено: обычных {normalCount} + случайных {randomCount}",
            "events.status.reloadFailed": "Ошибка обновления: {error}",
            "events.status.noVisibleEvents": "Нет видимых событий для теста",
            "events.status.noEventSelected": "Событие не выбрано",
            "events.status.opened": "Открыто: {name}",
            "events.status.openFailed": "Не удалось открыть: {error}",
            "events.details.noEventsLoaded": "События не загружены",
            "events.details.noEventSelected": "Событие не выбрано",

            # Events catalog tab
            "events.catalog.search": "Поиск",
            "events.catalog.kind.normal": "Обычные",
            "events.catalog.kind.random": "Случайные",
            "events.catalog.column.type": "Тип",
            "events.catalog.column.label": "Название",
            "events.catalog.column.id": "Id",
            "events.catalog.column.cost": "Цена",
            "events.catalog.column.prob": "Шанс",
            "events.catalog.details.title": "Определение",
            "events.catalog.button.copyId": "Коп. Id",
            "events.catalog.button.copyJson": "Коп. JSON",
            "events.catalog.button.testAll.ready": "Тест всех (x5)",
            "events.catalog.button.testAll.armed": "Тест всех ({count}/5)",
            "events.catalog.details.noMatching": "Нет подходящих событий",

            # Events random tab
            "events.random.endpoint.label": "RimWorld эндпоинт:",
            "events.random.endpoint.help": "(настраивается в Настройках)",
            "events.random.header.tags": "Теги",
            "events.random.header.enabled": "Включённые события",
            "events.random.tags.search": "Поиск",
            "events.random.tags.all": "Все",
            "events.random.tags.none": "Ни одного",
            "events.random.tags.noMatch": "Нет тегов по запросу",
            "events.random.enabled.search": "Поиск",
            "events.random.enabled.toggleHint": "Двойной клик или Пробел — переключить",
            "events.random.controls.duration": "Длительность (сек)",
            "events.random.controls.start": "Старт",
            "events.random.controls.stop": "Стоп",
            "events.random.status.votingStarted": "Голосование запущено",
            "events.random.status.stopped": "Остановлено",
            "events.random.status.noEnabled": "Нет включённых событий (проверь теги)",
            "events.random.status.newRound": "Начат новый раунд",
            "events.random.status.noWinner": "Победителя нет (нет голосов)",
            "events.random.status.executed": "Выполнено: {display} ({summary})",
            "events.random.status.executionFailed": "Ошибка выполнения: {error}",

            # Events editor tab
            "events.editor.templates": "Шаблоны",
            "events.editor.button.copyJson": "Коп. JSON",
            "events.editor.button.execute": "Выполнить",
            "events.editor.button.refreshLists": "Обновить списки",
            "events.editor.preview.title": "Сгенерированный JSON",
            "events.editor.parameters.endpoint": "Эндпоинт: {endpoint}",
            "events.editor.status.refreshedLookups": "Списки обновлены",
            "events.editor.status.templateBuildFailed": "Ошибка сборки шаблона: {error}",
            "events.editor.preview.noTemplateSelected": "Шаблон не выбран",
            "events.editor.status.copiedJson": "JSON скопирован",
            "events.editor.status.invalidEventJson": "Неверный JSON события: {error}",
            "events.editor.status.executed": "Выполнено: {label} ({summary})",
            "events.editor.status.executeFailed": "Не удалось выполнить: {error}",

            # Protection status
            "protection.label.unknown": "Защита: ?",
            "protection.label.off": "Защита: ВЫКЛ",
            "protection.label.external": "Защита: ОТ ДРУГИХ ({seconds}с)",
            "protection.label.allBad": "Защита: ОТ ПЛОХОГО ({seconds}с)",
            "protection.label.error": "Защита: {message}",
            "protection.error.unavailable": "недоступно",

            # Event tester
            "eventTest.running": "Тестирую {count} событий… запись в {fileName}",
            "eventTest.progress": "[{index}/{count}] {label} ({seconds:.1f}с)",
            "eventTest.complete": "Тест завершён: {path}",
            "eventTest.failed": "Тест провален: {error}",

            # Overlay
            "overlay.title": "Оверлей голосования",
            "overlay.button.close": "Закрыть",
            "overlay.poll.title": "Опрос",
            "overlay.poll.totalVotes": "Всего голосов: {count}",
            "overlay.poll.waitingVotes": "Ожидание голосов",
            "overlay.poll.noOptions": "Нет вариантов",
            "overlay.poll.recentVotersPrefix": "Недавние",
        },
    )
